/* confdefs.h */
#define PACKAGE_NAME "chikkooos"
#define PACKAGE_TARNAME "chikkooos"
#define PACKAGE_VERSION "1.0"
#define PACKAGE_STRING "chikkooos 1.0"
#define PACKAGE_BUGREPORT "chikkusoftwares@gmail.com"
#define PACKAGE_URL ""
#define PACKAGE "chikkooos"
#define VERSION "1.0"
#define RDEBUG 1
#define RGLERRORTRACE 1
#define HAVE_BULLET 1
#define HAVE_BOX2D 1
#define HAVE_CHIPMUNK 1
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define STDC_HEADERS 1
#define HAVE_GL_GLUT_H 1
#define HAVE_GL_GL_H 1
